### ISSUE TITLE
Env. vars should have a dedicated section

### ISSUE THREAD

**Issue by Sl-Alex** [Sl-Alex/pyapitester#10]
Right now, all variables are in the root. It would be nice to move them to a separate section:
```toml
[vars]
var1 = 'value1'
var2 = true
var3 = 2345
# and so on
```

It makes sense, because *.env files will be extended with proxy configuration and other parameters.
